### PR TITLE
Swaps fixes

### LINKED ISSUE #835: [DEX] [Swap] Amount Input Should Be Based On Minimum Tick Size
### **Steps to Reproduce**
1. Go to /swap
2. Observe amount input placeholder
3. Provide input for amout

### **Actual Behaviour**
- The amount input placeholder is always with 4dp precision.
- The amount input is not limited by any constraint (i.e. users can input any length of numerical input)

### **Expected Behaviour**
- The amount input placeholder should be based on minimum tick size (min price tick for quote currency, min quantity tick for base currency)
- The amount input should be limited by minimum tick size (min price tick for quote currency, min quantity tick for base currency)

### PR DESCRIPTION
**Pull request by afterburn**
This PR should resolve the swap issues found in the [Swaps QA](https://www.notion.so/injective/Swaps-QA-d692ad365cf54d18ba39f2d06d1387fc) doc.

### CODE REVIEW

File: components/partials/swap/index.vue [hunk 1]
```diff
@@ -1473,46 +1536,71 @@ export default Vue.extend({
...
-      this.form.amount = quantity
+      if (!fromToken) {
+        return
+      }
 
-      this.form.toAmount = toQuantity.toFormat(
-        orderTypeBuy ? market?.priceDecimals : market?.quantityDecimals
-      )
+      const decimalPlaces = orderTypeBuy
+        ? market?.priceDecimals
```
Comment (bangjelkoski) [inline components/partials/swap/index.vue:1558]: Let's do an early return if the market is undefined 

```
if (!market) {
    return
}
```

this should actually never happen (market being undefined) so its fine to have an early return

**Review by bangjelkoski — CHANGES_REQUESTED** [review]

**Review by shane-moore — APPROVED** [review]
